#!/bin/sh

LIB_DIR=lib

echo "$@" | grep "\-d" > /dev/null
if [ $? -eq 0 ] ; then
	#DEBUG="-Djavax.net.debug=all -Dsmack.debugEnabled=true -Dsun.security.krb5.debug=true -Djava.util.logging.config.file=logging.properties"
	DEBUG="-Dsmack.debugEnabled=true -Dsun.security.krb5.debug=true -Djava.util.logging.config.file=~/.xat/logging.properties"
else
	DEBUG=""
fi

java $DEBUG \
	-Djavax.security.auth.login.config=~/.xat/gss.conf \
	-Dsun.security.jgss.native=true \
	-Dsun.security.jgss.lib=/usr/lib/libgssapi_krb5.so.2.2 \
	-cp $LIB_DIR/commons-cli-1.1.jar:$LIB_DIR/nanoxml-lite-2.2.3.jar:$LIB_DIR/smack.jar:$LIB_DIR/smackx.jar:$LIB_DIR/xat.jar \
	com.darianpatrick.XmppAdminTool "$@"
	#-Djavax.security.auth.useSubjectCredsOnly=false \

